# Last Name: Amores
# First Name: Anne Christine
# Student Number: 202104650

### Question Number: 1
# "1" belongs to the character data type, while 1 belongs to the numeric data type. 
# Additionally, 1L is categorized under the integer data type, and 1 + 0i is associated with the complex data type.

### Question Number: 2
# This vector will be saved as a character because of the presence of the character "1" in the vector.
# The reason for this is that the character data type is the most generic data type and the others will be coerced into it.
# Any other type of data can easily be expressed as a character, but the converse is not true.

### Question Number: 3 
# The command 10:0 generates a vector with the integers from 0 to 10 in descending order.
# The command seq_len(20) generates a sequence of integers from 1 to 20.
# The command seq_along(10:0) generates a sequence of integers from 1 up to 11, because the input vector 10:0 contains 11 elements.

### Question Number: 4
# [41] indicates that the first value in that output line corresponds to the 41st element of the vector generated by the seq(5, 15, by=0.231) command.

### Question Number: 5
My_Mat <- matrix(seq(1.000, 2.320, by = 0.055), nrow = 5, ncol = 5)
My_Mat

### Question Number 6:
# We issue the rownames() and colnames() command, respectively.
rownames(My_Mat) <- c("Row 1", "Row 2", "Row 3", "Row 4", "Row 5")
colnames(My_Mat) <- c("Column 1", "Column 2", "Column 3", "Column 4", "Column 5")
My_Mat

### Question Number 7: 
My_Df <- data.frame ("Name"="Anne Christine Amores", "Age"=19, "Birthday"="26-04-2004", "Height"=156, "Weight"=60)
My_Df

### Question Number 8: 
My_Df[1,"BMI"] <- My_Df[1,"Weight"]/(My_Df[1,"Height"]/100)^2
My_Df
# The BMI is computed by dividing the weight (in kg) by the square of the height (converted to m) by extracting the element under "Weight" from row 1 and the element under "Height" from row 1.
# The command inserts a new column in the data frame labeled "BMI" and assigns the computed value under that column to the first (and only) row of the data frame.